configurations:
    - source: settings/environment.example.py
      destination: settings/environment.py

directories:
    - path: media/js
      permissions: '777'
    - path: media/css
      permissions: '777'

#dummy:
#    fixtures:
#        - myapp/fixtures/dummy.json
#    files:
#        - source: media/images.dummy/*
#          destination: media/images/
#
#cron:
#    - script: cron/update.py
#      schedule: '0 0 * * *'
